export const animatedComponent = 'animate__animated';

export const animationSpeeds = {
    slowest: 'animate__slower',
    slow: 'animate__slow',
    fast: 'animate__fast',
    fastest: 'animate__faster',
};

export const animationDelays = {
    delay2: 'animate__delay-2s',
    delay3: 'animate__delay-3s',
    delay4: 'animate__delay-4s',
    delay5: 'animate__delay-5s',
};

export const animationDuration = {
    repeat1: 'animate__repeat-1',
    repeat2: 'animate__repeat-2',
    repeat3: 'animate__repeat-3',
    infinite: 'animate__infinite',
};

export const animations = {
    specials: {
        hinge: 'animate__hinge',
        jackInTheBox: 'animate__jackInTheBox',
        rollIn: 'animate__rollIn',
        rollOut: 'animate__rollOut',
    },
    entrances: {
        backInDown: 'animate__backInDown',
        backInUp: 'animate__backInUp',
        backInLeft: 'animate__backInLeft',
        backInRight: 'animate__backInDown',
        bounceInDown: 'animate__bounceInDown',
        bounceInUp: 'animate__bounceInUp',
        bounceInLeft: 'animate__bounceInLeft',
        bounceInRight: 'animate__bounceInDown',
        fadeIn: 'animate__fadeIn',
        fadeInDown: 'animate__fadeInDown',
        fadeInDownBig: 'animate__fadeInDownBig',
        fadeInUp: 'animate__fadeInUp',
        fadeInUpBig: 'animate__fadeInUpBig',
        fadeInLeft: 'animate__fadeInLeft',
        fadeInLeftBig: 'animate__fadeInLeftBig',
        fadeInRight: 'animate__fadeInDown',
        fadeInRightBig: 'animate__fadeInDownBig',
        fadeInTopLeft: 'animate__fadeInTopLeft',
        fadeInTopRight: 'animate__fadeInTopRight',
        fadeInBottomLeft: 'animate__fadeInBottomLeft',
        fadeInBottomRight: 'animate__fadeInBottomRight',
        zoomIn: 'animate__zoomIn',
        zoomInDown: 'animate__zoomInDown',
        zoomInUp: 'animate__zoomInUp',
        zoomInLeft: 'animate__zoomInLeft',
        zoomInRight: 'animate__zoomInDown',
        slideInDown: 'animate__slideInDown',
        slideInUp: 'animate__slideInUp',
        slideInLeft: 'animate__slideInLeft',
        slideInRight: 'animate__slideInDown',
        rotateIn: 'animate__rotateIn',
        rotateInDown: 'animate__rotateInDown',
        rotateInUp: 'animate__rotateInUp',
        rotateInLeft: 'animate__rotateInLeft',
        rotateInRight: 'animate__rotateInDown',
    },
    exits: {
        backOutDown: 'animate__backOutDown',
        backOutUp: 'animate__backOutUp',
        backOutLeft: 'animate__backOutLeft',
        backOutRight: 'animate__backOutRight',
        bounceOutDown: 'animate__bounceOutDown',
        bounceOutUp: 'animate__bounceOutUp',
        bounceOutLeft: 'animate__bounceOutLeft',
        bounceOutRight: 'animate__bounceOutRight',
        fadeOut: 'animate__fadeOut',
        fadeOutDown: 'animate__fadeOutDown',
        fadeOutDownBig: 'animate__fadeOutDownBig',
        fadeOutUp: 'animate__fadeOutUp',
        fadeOutUpBig: 'animate__fadeOutUpBig',
        fadeOutLeft: 'animate__fadeOutLeft',
        fadeOutLeftBig: 'animate__fadeOutLeftBig',
        fadeOutRight: 'animate__fadeOutDown',
        fadeOutRightBig: 'animate__fadeOutDownBig',
        fadeOutTopLeft: 'animate__fadeOutTopLeft',
        fadeOutTopRight: 'animate__fadeOutTopRight',
        fadeOutBottomLeft: 'animate__fadeOutBottomLeft',
        fadeOutBottomRight: 'animate__fadeOutBottomRight',
        zoomOut: 'animate__zoomOut',
        zoomOutDown: 'animate__zoomOutDown',
        zoomOutUp: 'animate__zoomOutUp',
        zoomOutLeft: 'animate__zoomOutLeft',
        zoomOutRight: 'animate__zoomOutRight',
        slideOutDown: 'animate__slideOutDown',
        slideOutUp: 'animate__slideOutUp',
        slideOutLeft: 'animate__slideOutLeft',
        slideOutRight: 'animate__slideOutRight',
        rotateOut: 'animate__rotateOut',
        rotateOutDown: 'animate__rotateOutDown',
        rotateOutUp: 'animate__rotateOutUp',
        rotateOutLeft: 'animate__rotateOutLeft',
        rotateOutRight: 'animate__rotateOutRight',
    },
    flippers: {
        flipIn: 'animate__flip',
        flipInX: 'animate__flipInX',
        flipInY: 'animate__flipInY',
        flipInOutX: 'animate__flipOutX',
        flipInOutY: 'animate__flipOutY',
    },
    attention_seekers: {
        bounce: 'animate__bounce',
        flash: 'animate__flash',
        pulse: 'animate__pulse',
        rubberBand: 'animate__rubberBand',
        shakeX: 'animate__shakeX',
        shakeY: 'animate__shakeY',
        headShake: 'animate__headShake',
        swing: 'animate__swing',
        tada: 'animate__tada',
        wobble: 'animate__wobble',
        jello: 'animate__jello',
        heartBeat: 'animate__heartBeat',
    },
};
